/*
 * Decompiled with CFR 0_129.
 */
package me.skorrloregaming;

import me.skorrloregaming.Go;
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.Recipe;
import org.bukkit.inventory.ShapedRecipe;
import org.bukkit.inventory.ShapelessRecipe;

public class CustomRecipes {
	public static void loadRecipes() {
		ItemStack stack = Go.createMaterial(Material.ELYTRA,  ChatColor.RESET + "Elytra");
		ShapedRecipe elytra = new ShapedRecipe(stack);
		elytra.shape(new String[]{"ABA", "BDB", "BCB"});
		elytra.setIngredient('A', Material.AIR);
		elytra.setIngredient('B', Material.LEATHER);
		elytra.setIngredient('C', Material.EYE_OF_ENDER);
		elytra.setIngredient('D', Material.DIAMOND);
		Bukkit.getServer().addRecipe((Recipe) elytra);
		ShapedRecipe endPortal = new ShapedRecipe(Go.createMaterial(Material.EYE_OF_ENDER,  ChatColor.LIGHT_PURPLE + "End Portal"));
		endPortal.shape(new String[]{"BCB", "BDB", "AAA"});
		endPortal.setIngredient('A', Material.OBSIDIAN);
		endPortal.setIngredient('B', Material.GLASS);
		endPortal.setIngredient('C', Material.ENDER_PEARL);
		endPortal.setIngredient('D', Material.NETHER_STAR);
		Bukkit.getServer().addRecipe((Recipe) endPortal);
		ShapelessRecipe sulphur = new ShapelessRecipe(Go.createMaterial(Material.SULPHUR, 1));
		sulphur.addIngredient(1, Material.FLINT);
		Bukkit.getServer().addRecipe((Recipe) sulphur);
		ShapelessRecipe explosiveSulphur0 = new ShapelessRecipe(Go.createMaterial(Material.SULPHUR, 1,  ChatColor.LIGHT_PURPLE + "Explosive Gunpowder"));
		explosiveSulphur0.addIngredient(4, Material.SULPHUR);
		Bukkit.getServer().addRecipe((Recipe) explosiveSulphur0);
		ShapelessRecipe stone = new ShapelessRecipe(Go.createMaterial(Material.STONE, 3));
		stone.addIngredient(3, Material.COBBLESTONE);
		stone.addIngredient(1, Material.COAL);
		Bukkit.getServer().addRecipe((Recipe) stone);
		ShapelessRecipe vial0 = new ShapelessRecipe(Go.createMaterial(Material.MONSTER_EGG,  ChatColor.RESET + "Monster Vial"));
		vial0.addIngredient(1, Material.GLASS_BOTTLE);
		Bukkit.getServer().addRecipe((Recipe) vial0);
		ShapelessRecipe vial1 = new ShapelessRecipe(Go.createMaterial(Material.GLASS_BOTTLE));
		vial1.addIngredient(1, Material.MONSTER_EGG);
		Bukkit.getServer().addRecipe((Recipe) vial1);
		ShapedRecipe chainHelmet = new ShapedRecipe(Go.createMaterial(Material.CHAINMAIL_HELMET));
		chainHelmet.shape(new String[]{"BBB", "BAB", "AAA"});
		chainHelmet.setIngredient('A', Material.AIR);
		chainHelmet.setIngredient('B', Material.IRON_FENCE);
		Bukkit.getServer().addRecipe((Recipe) chainHelmet);
		ShapedRecipe chainChestplate = new ShapedRecipe(Go.createMaterial(Material.CHAINMAIL_CHESTPLATE));
		chainChestplate.shape(new String[]{"BAB", "BBB", "BBB"});
		chainChestplate.setIngredient('A', Material.AIR);
		chainChestplate.setIngredient('B', Material.IRON_FENCE);
		Bukkit.getServer().addRecipe((Recipe) chainChestplate);
		ShapedRecipe chainLeggings = new ShapedRecipe(Go.createMaterial(Material.CHAINMAIL_LEGGINGS));
		chainLeggings.shape(new String[]{"BBB", "BAB", "BAB"});
		chainLeggings.setIngredient('A', Material.AIR);
		chainLeggings.setIngredient('B', Material.IRON_FENCE);
		Bukkit.getServer().addRecipe((Recipe) chainLeggings);
		ShapedRecipe chainBoots = new ShapedRecipe(Go.createMaterial(Material.CHAINMAIL_BOOTS));
		chainBoots.shape(new String[]{"BAB", "BAB"});
		chainBoots.setIngredient('A', Material.AIR);
		chainBoots.setIngredient('B', Material.IRON_FENCE);
		Bukkit.getServer().addRecipe((Recipe) chainBoots);
		ShapelessRecipe stoneBrickToCobble = new ShapelessRecipe(Go.createMaterial(Material.COBBLESTONE, 3));
		stoneBrickToCobble.addIngredient(1, Material.SMOOTH_BRICK);
		Bukkit.getServer().addRecipe((Recipe) stoneBrickToCobble);
		ShapelessRecipe diamond0 = new ShapelessRecipe(Go.createMaterial(Material.DIAMOND, 2));
		diamond0.addIngredient(1, Material.DIAMOND_SWORD);
		Bukkit.getServer().addRecipe((Recipe) diamond0);
		ShapelessRecipe diamond1 = new ShapelessRecipe(Go.createMaterial(Material.DIAMOND, 3));
		diamond1.addIngredient(1, Material.DIAMOND_PICKAXE);
		Bukkit.getServer().addRecipe((Recipe) diamond1);
		ShapelessRecipe diamond2 = new ShapelessRecipe(Go.createMaterial(Material.DIAMOND, 3));
		diamond2.addIngredient(1, Material.DIAMOND_AXE);
		Bukkit.getServer().addRecipe((Recipe) diamond2);
		ShapelessRecipe diamond3 = new ShapelessRecipe(Go.createMaterial(Material.DIAMOND, 1));
		diamond3.addIngredient(1, Material.DIAMOND_SPADE);
		Bukkit.getServer().addRecipe((Recipe) diamond3);
		ShapelessRecipe diamond4 = new ShapelessRecipe(Go.createMaterial(Material.DIAMOND, 5));
		diamond4.addIngredient(1, Material.DIAMOND_HELMET);
		Bukkit.getServer().addRecipe((Recipe) diamond4);
		ShapelessRecipe diamond5 = new ShapelessRecipe(Go.createMaterial(Material.DIAMOND, 8));
		diamond5.addIngredient(1, Material.DIAMOND_CHESTPLATE);
		Bukkit.getServer().addRecipe((Recipe) diamond5);
		ShapelessRecipe diamond6 = new ShapelessRecipe(Go.createMaterial(Material.DIAMOND, 7));
		diamond6.addIngredient(1, Material.DIAMOND_LEGGINGS);
		Bukkit.getServer().addRecipe((Recipe) diamond6);
		ShapelessRecipe diamond7 = new ShapelessRecipe(Go.createMaterial(Material.DIAMOND, 4));
		diamond7.addIngredient(1, Material.DIAMOND_BOOTS);
		Bukkit.getServer().addRecipe((Recipe) diamond7);
		ShapelessRecipe iron0 = new ShapelessRecipe(Go.createMaterial(Material.IRON_INGOT, 2));
		iron0.addIngredient(1, Material.IRON_SWORD);
		Bukkit.getServer().addRecipe((Recipe) iron0);
		ShapelessRecipe iron1 = new ShapelessRecipe(Go.createMaterial(Material.IRON_INGOT, 3));
		iron1.addIngredient(1, Material.IRON_PICKAXE);
		Bukkit.getServer().addRecipe((Recipe) iron1);
		ShapelessRecipe iron2 = new ShapelessRecipe(Go.createMaterial(Material.IRON_INGOT, 3));
		iron2.addIngredient(1, Material.IRON_AXE);
		Bukkit.getServer().addRecipe((Recipe) iron2);
		ShapelessRecipe iron3 = new ShapelessRecipe(Go.createMaterial(Material.IRON_INGOT, 1));
		iron3.addIngredient(1, Material.IRON_SPADE);
		Bukkit.getServer().addRecipe((Recipe) iron3);
		ShapelessRecipe iron4 = new ShapelessRecipe(Go.createMaterial(Material.IRON_INGOT, 5));
		iron4.addIngredient(1, Material.IRON_HELMET);
		Bukkit.getServer().addRecipe((Recipe) iron4);
		ShapelessRecipe iron5 = new ShapelessRecipe(Go.createMaterial(Material.IRON_INGOT, 8));
		iron5.addIngredient(1, Material.IRON_CHESTPLATE);
		Bukkit.getServer().addRecipe((Recipe) iron5);
		ShapelessRecipe iron6 = new ShapelessRecipe(Go.createMaterial(Material.IRON_INGOT, 7));
		iron6.addIngredient(1, Material.IRON_LEGGINGS);
		Bukkit.getServer().addRecipe((Recipe) iron6);
		ShapelessRecipe iron7 = new ShapelessRecipe(Go.createMaterial(Material.IRON_INGOT, 4));
		iron7.addIngredient(1, Material.IRON_BOOTS);
		Bukkit.getServer().addRecipe((Recipe) iron7);
		ShapelessRecipe gold0 = new ShapelessRecipe(Go.createMaterial(Material.GOLD_INGOT, 2));
		gold0.addIngredient(1, Material.GOLD_SWORD);
		Bukkit.getServer().addRecipe((Recipe) gold0);
		ShapelessRecipe gold1 = new ShapelessRecipe(Go.createMaterial(Material.GOLD_INGOT, 3));
		gold1.addIngredient(1, Material.GOLD_PICKAXE);
		Bukkit.getServer().addRecipe((Recipe) gold1);
		ShapelessRecipe gold2 = new ShapelessRecipe(Go.createMaterial(Material.GOLD_INGOT, 3));
		gold2.addIngredient(1, Material.GOLD_AXE);
		Bukkit.getServer().addRecipe((Recipe) gold2);
		ShapelessRecipe gold3 = new ShapelessRecipe(Go.createMaterial(Material.GOLD_INGOT, 1));
		gold3.addIngredient(1, Material.GOLD_SPADE);
		Bukkit.getServer().addRecipe((Recipe) gold3);
		ShapelessRecipe gold4 = new ShapelessRecipe(Go.createMaterial(Material.GOLD_INGOT, 5));
		gold4.addIngredient(1, Material.GOLD_HELMET);
		Bukkit.getServer().addRecipe((Recipe) gold4);
		ShapelessRecipe gold5 = new ShapelessRecipe(Go.createMaterial(Material.GOLD_INGOT, 8));
		gold5.addIngredient(1, Material.GOLD_CHESTPLATE);
		Bukkit.getServer().addRecipe((Recipe) gold5);
		ShapelessRecipe gold6 = new ShapelessRecipe(Go.createMaterial(Material.GOLD_INGOT, 7));
		gold6.addIngredient(1, Material.GOLD_LEGGINGS);
		Bukkit.getServer().addRecipe((Recipe) gold6);
		ShapelessRecipe gold7 = new ShapelessRecipe(Go.createMaterial(Material.GOLD_INGOT, 4));
		gold7.addIngredient(1, Material.GOLD_BOOTS);
		Bukkit.getServer().addRecipe((Recipe) gold7);
		ShapelessRecipe ironBarding = new ShapelessRecipe(Go.createMaterial(Material.IRON_INGOT, 6));
		ironBarding.addIngredient(1, Material.IRON_BARDING);
		Bukkit.getServer().addRecipe((Recipe) ironBarding);
		ShapelessRecipe diamondBarding = new ShapelessRecipe(Go.createMaterial(Material.DIAMOND, 6));
		diamondBarding.addIngredient(1, Material.DIAMOND_BARDING);
		Bukkit.getServer().addRecipe((Recipe) diamondBarding);
		ShapelessRecipe goldBarding = new ShapelessRecipe(Go.createMaterial(Material.GOLD_INGOT, 6));
		goldBarding.addIngredient(1, Material.GOLD_BARDING);
		Bukkit.getServer().addRecipe((Recipe) goldBarding);
	}
}

